<a href="https://colab.research.google.com/github/viett887g/numpy4/blob/main/numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import statistics
from statistics import mode

In [ ]:
Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình)
np.arrange()
np.linspace()
np.logspace()
np.random.rand()

In [22]:
vecA = [np.arange(1,10)]

def magie():
    vecA = np.arange(1,8)
    vecB = []
    for i in range(7):
        vecB.append(vecA)
        print("số chiều của vector ", str(i+1),"la", vecA.ndim)
        print("số chiều của vector chuyển vị ", str(i+1), "la",np.transpose([vecA]).ndim)
        print("kích thước của vector A ", str(i+1),"la" ,vecA.shape)
        print("kích thước của vector A chuyển vị " ,str(i+1), "la",np.transpose([vecA]).shape)
    vecA = np.array(vecB)
    return vecA

vecA = magie()
print(vecA)

số chiều của vector  1 la 1
số chiều của vector chuyển vị  1 la 2
kích thước của vector A  1 la (7,)
kích thước của vector A chuyển vị  1 la (7, 1)
số chiều của vector  2 la 1
số chiều của vector chuyển vị  2 la 2
kích thước của vector A  2 la (7,)
kích thước của vector A chuyển vị  2 la (7, 1)
số chiều của vector  3 la 1
số chiều của vector chuyển vị  3 la 2
kích thước của vector A  3 la (7,)
kích thước của vector A chuyển vị  3 la (7, 1)
số chiều của vector  4 la 1
số chiều của vector chuyển vị  4 la 2
kích thước của vector A  4 la (7,)
kích thước của vector A chuyển vị  4 la (7, 1)
số chiều của vector  5 la 1
số chiều của vector chuyển vị  5 la 2
kích thước của vector A  5 la (7,)
kích thước của vector A chuyển vị  5 la (7, 1)
số chiều của vector  6 la 1
số chiều của vector chuyển vị  6 la 2
kích thước của vector A  6 la (7,)
kích thước của vector A chuyển vị  6 la (7, 1)
số chiều của vector  7 la 1
số chiều của vector chuyển vị  7 la 2
kích thước của vector A  7 la (7,)
kích thước 

In [ ]:
Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A được sinh bởi:

np.arrange()
np.linspace()
np.logspace()
np.random.rand() Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
Số chiều và kích thước của ma trận A và ma trận AT

In [33]:
def magieclo(x,y):
    a = np.arange(1,x+1)
    b = []
    for i in range(y):
        b.append(a)
        print("\nMa trận A được tạo ra lần ",str(i+1) ," là: \n", np.array(b))
        print("\nKích thước của ma trận A được tạo ra lần ",str(i+1) ," là: ", np.array(b).shape)
        c = np.transpose(b)
        print("\nMa trận chuuyển vị của A được tạo ra lần ",str(i+1) ," là: \n", c)
        print("\nKích thước của ma trận chuyển vị A được tạo ra lần ",str(i+1) ," là: ", c.shape)
    a = np.array(b)
    
    return a

A = magieclo(10, 7)
print(A)


Ma trận A được tạo ra lần  1  là: 
 [[ 1  2  3  4  5  6  7  8  9 10]]

Kích thước của ma trận A được tạo ra lần  1  là:  (1, 10)

Ma trận chuuyển vị của A được tạo ra lần  1  là: 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

Kích thước của ma trận chuyển vị A được tạo ra lần  1  là:  (10, 1)

Ma trận A được tạo ra lần  2  là: 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]

Kích thước của ma trận A được tạo ra lần  2  là:  (2, 10)

Ma trận chuuyển vị của A được tạo ra lần  2  là: 
 [[ 1  1]
 [ 2  2]
 [ 3  3]
 [ 4  4]
 [ 5  5]
 [ 6  6]
 [ 7  7]
 [ 8  8]
 [ 9  9]
 [10 10]]

Kích thước của ma trận chuyển vị A được tạo ra lần  2  là:  (10, 2)

Ma trận A được tạo ra lần  3  là: 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]

Kích thước của ma trận A được tạo ra lần  3  là:  (3, 10)

Ma trận chuuyển vị của A được tạo ra lần  3  là: 
 [[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [ 4  4  4]
 [ 5  5  5]
 [ 6 

In [ ]:
Câu 3: Sử dụng thư viện Numpy, hãy:

In [ ]:
Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())

In [34]:
veca = A.flatten()
print(veca)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4
  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8
  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


In [ ]:
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [35]:
vecb = np.array(A).reshape(7,10)
print(vecb)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
Câu 4: Sử dụng thư viện Numpy, hãy:

Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [46]:
vecc = np.logspace(11,21, 10)
vecd = []
for i in range(15):
    vecd.append(vecc)
vecd = np.array(vecd)

In [47]:
print(vecd)

[[1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e+14
  2.78255940e+15 3.59381366e+16 4.64158883e+17 5.99484250e+18
  7.74263683e+19 1.00000000e+21]
 [1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e+14
  2.78255940e+15 3.59381366e+16 4.64158883e+17 5.99484250e+18
  7.74263683e+19 1.00000000e+21]
 [1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e+14
  2.78255940e+15 3.59381366e+16 4.64158883e+17 5.99484250e+18
  7.74263683e+19 1.00000000e+21]
 [1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e+14
  2.78255940e+15 3.59381366e+16 4.64158883e+17 5.99484250e+18
  7.74263683e+19 1.00000000e+21]
 [1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e+14
  2.78255940e+15 3.59381366e+16 4.64158883e+17 5.99484250e+18
  7.74263683e+19 1.00000000e+21]
 [1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e+14
  2.78255940e+15 3.59381366e+16 4.64158883e+17 5.99484250e+18
  7.74263683e+19 1.00000000e+21]
 [1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e

In [49]:
print(vecd[2])

[1.00000000e+11 1.29154967e+12 1.66810054e+13 2.15443469e+14
 2.78255940e+15 3.59381366e+16 4.64158883e+17 5.99484250e+18
 7.74263683e+19 1.00000000e+21]


In [50]:
print(vecd[:,4])

[2.7825594e+15 2.7825594e+15 2.7825594e+15 2.7825594e+15 2.7825594e+15
 2.7825594e+15 2.7825594e+15 2.7825594e+15 2.7825594e+15 2.7825594e+15
 2.7825594e+15 2.7825594e+15 2.7825594e+15 2.7825594e+15 2.7825594e+15]
